[stage]
texture = "stages/stage.png"
pos_x = 0.0
pos_y = -120.0
scale = 4.0
ground_y = -310.0

[[fighters]]
name = "P1"
player_id = 1
pos_x = -140.0
pos_y = 0.0
scale = 6.5
flip_x = false
movement_speed = 220.0
shuriken_texture = "characters/p1SHURIKEN.png"
shuriken_speed = 420.0
shuriken_lifetime = 1.6
shuriken_scale = 6.0

[fighters.animations.idle]
texture = "characters/p1IDLE.png"
frame_width = 96
frame_height = 96
columns = 10
rows = 1
first = 0
last = 9
fps = 10.0
looping = true

[fighters.animations.walk]
texture = "characters/p1RUN.png"
frame_width = 96
frame_height = 96
columns = 16
rows = 1
first = 0
last = 15
fps = 14.0
looping = true

[fighters.animations.attack]
texture = "characters/p1ATTACK 1.png"
frame_width = 96
frame_height = 96
columns = 7
rows = 1
first = 0
last = 6
fps = 14.0
looping = false

[fighters.animations.throw]
texture = "characters/p1THROW.png"
frame_width = 96
frame_height = 96
columns = 7
rows = 1
first = 0
last = 6
fps = 14.0
looping = false


[[fighters]]
name = "P2"
player_id = 2
pos_x = 140.0
pos_y = 0.0
scale = 6.5
flip_x = true
movement_speed = 220.0
shuriken_texture = "characters/p2SHURIKEN.png"
shuriken_speed = 420.0
shuriken_lifetime = 1.6
shuriken_scale = 6.0

[fighters.animations.idle]
texture = "characters/p2IDLE.png"
frame_width = 96
frame_height = 64
columns = 5
rows = 1
first = 0
last = 4
fps = 10.0
looping = true

[fighters.animations.walk]
texture = "characters/p2RUN.png"
frame_width = 96
frame_height = 64
columns = 7
rows = 1
first = 0
last = 6
fps = 14.0
looping = true

[fighters.animations.attack]
texture = "characters/p2ATTACK1.png"
frame_width = 96
frame_height = 64
columns = 5
rows = 1
first = 0
last = 4
fps = 14.0
looping = false

[fighters.animations.throw]
texture = "characters/p2THROW.png"
frame_width = 96
frame_height = 64
columns = 7
rows = 1
first = 0
last = 6
fps = 14.0
looping = false
